prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'jenkins'
        static_configs:
          - targets: ['192.168.30.2:8080']
        metrics_path: '/prometheus/metrics/'
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
    ruleSelector:
      matchLabels:
        role: kubernetes-pod-alerts

alertmanager:
  alertmanagerSpec:
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['job']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'discord'
      receivers:
        - name: 'discord'
          webhook_configs:
            - url: 'https://discord.com/api/webhooks/1244807716522688633/_BDDdlYOj9kA_nKHVL7soWmOSvz2_O2gpkWoaT6VybPdm2Db4zwBmDv9zNxWW8OC5d-F'

grafana:
  service:
    type: NodePort
    port: 80
    targetPort: 3000
  ingress:
    enabled: false
  grafana.ini:
    server:
      root_url: http://localhost:3000
    users:
      default_theme: light
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-kube-prometheus-prometheus
          isDefault: true
  dashboards:
    default:
      kube-prometheus:
        gnetId: 6417
        revision: 1
        datasource: Prometheus
