prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'jenkins'
        static_configs:
          - targets: ['192.168.30.2:8080']
        metrics_path: '/prometheus/metrics/'
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
    ruleSelector:
      matchLabels:
        role: kubernetes-pod-alerts
  additionalPrometheusRules:
    - name: kubernetes-pod-alerts
      groups:
      - name: kubernetes-pods
        rules:
        - alert: PodNotRunning
          expr: kube_pod_status_phase{phase=~"Failed|Unknown"} > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Pod not running in {{ $labels.namespace }}"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in a {{ $labels.phase }} state for more than 5 minutes."
        - alert: PodDeleted
          expr: kube_pod_deleted > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod deleted in {{ $labels.namespace }}"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been deleted."

alertmanager:
  alertmanagerSpec:
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['alertname']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'discord'
      receivers:
        - name: 'discord'
          webhook_configs:
            - url: 'https://discord.com/api/webhooks/1244807716522688633/_BDDdlYOj9kA_nKHVL7soWmOSvz2_O2gpkWoaT6VybPdm2Db4zwBmDv9zNxWW8OC5d-F'  # Remplacez par l'URL de votre webhook Discord

grafana:
  service:
    type: NodePort
    port: 80
    targetPort: 3000
  ingress:
    enabled: false
  grafana.ini:
    server:
      root_url: http://localhost:3000
    users:
      default_theme: light
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-kube-prometheus-prometheus
          isDefault: true
  dashboards:
    default:
      kube-prometheus:
        gnetId: 6417
        revision: 1
        datasource: Prometheus
